version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: digital-ocean-primary-db
    ports:
      - "8886:3306"
    volumes:
      - ./mysql/.data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dockernet

networks:
  dockernet:
    external: true

